In [ ]:
!pip install datasets==2.19.0 pandas

Collecting datasets==2.19.0
  Downloading datasets-2.19.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets==2.19.0) (3.29.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from datasets==2.19.0) (2.0.2)
Requirement already satisfied: pyarrow>=12.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets==2.19.0) (18.1.0)
Collecting pyarrow-hotfix (from datasets==2.19.0)
  Downloading pyarrow_hotfix-0.7-py3-none-any.whl.metadata (3.6 kB)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets==2.19.0) (0.3.8)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.12/dist-packages (from datasets==2.19.0) (2.32.4)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.12/dist-packages (from datasets==2.19.0) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets==2.19.0) (3.6.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.12/dist-packages (from datasets==2.19.0) (0.70.16)
Collecting fsspec<=2024.3.1,>=2023.1.0 (from fsspec[http]<=2024.3.1,>=2023.1.0->datasets==2.19.0)
  Downloading fsspec-2024.3.1-py3-none-any.whl.metadata (6.8 kB)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.12/dist-packages (from datasets==2.19.0) (3.13.5)
Requirement already satisfied: huggingface-hub>=0.21.2 in /usr/local/lib/python3.12/dist-packages (from datasets==2.19.0) (1.11.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets==2.19.0) (26.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets==2.19.0) (6.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->datasets==2.19.0) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->datasets==2.19.0) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->datasets==2.19.0) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp->datasets==2.19.0) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp->datasets==2.19.0) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->datasets==2.19.0) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->datasets==2.19.0) (1.23.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.21.2->datasets==2.19.0) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.21.2->datasets==2.19.0) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.21.2->datasets==2.19.0) (0.24.2)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.21.2->datasets==2.19.0) (4.15.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->datasets==2.19.0) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->datasets==2.19.0) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->datasets==2.19.0) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->datasets==2.19.0) (2026.4.22)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.21.2->datasets==2.19.0) (4.13.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.21.2->datasets==2.19.0) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.21.2->datasets==2.19.0) (0.16.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.21.2->datasets==2.19.0) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.21.2->datasets==2.19.0) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.21.2->datasets==2.19.0) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.21.2->datasets==2.19.0) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.21.2->datasets==2.19.0) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.21.2->datasets==2.19.0) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub>=0.21.2->datasets==2.19.0) (0.1.2)
Downloading datasets-2.19.0-py3-none-any.whl (542 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 542.0/542.0 kB 12.2 MB/s eta 0:00:00
Downloading fsspec-2024.3.1-py3-none-any.whl (171 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 172.0/172.0 kB 6.9 MB/s eta 0:00:00
Downloading pyarrow_hotfix-0.7-py3-none-any.whl (7.9 kB)
Installing collected packages: pyarrow-hotfix, fsspec, datasets
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2025.3.0
    Uninstalling fsspec-2025.3.0:
      Successfully uninstalled fsspec-2025.3.0
  Attempting uninstall: datasets
    Found existing installation: datasets 4.0.0
    Uninstalling datasets-4.0.0:
      Successfully uninstalled datasets-4.0.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gcsfs 2025.3.0 requires fsspec==2025.3.0, but you have fsspec 2024.3.1 which is incompatible.
Successfully installed datasets-2.19.0 fsspec-2024.3.1 pyarrow-hotfix-0.7

In [ ]:
from datasets import load_dataset
import pandas as pd

print("Downloading the dataset...")
# 1. Download the German subset
dataset = load_dataset("BioMistral/BioInstructQA", "MedQA", trust_remote_code=True)
df = pd.DataFrame(dataset['test_german'])

# 2. Filter the dataset! We ONLY want MedQA, throw away MedMCQA and the others!
df_medqa = df[df['corpus_name'] == 'MedQA'].copy()

# 3. Save it to a clean CSV file
df_medqa.to_csv("Pure_German_MedQA.csv", index=False)

print(f"Success! Extracted {len(df_medqa)} pure German MedQA questions.")
print("\nHere is the first German question:")
print(df.iloc[0]['prompt_no_answer'])

Downloading the dataset...

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

Downloading builder script: 0.00B [00:00, ?B/s]

Downloading readme: 0.00B [00:00, ?B/s]

Downloading data:   0%|          | 0.00/485M [00:00<?, ?B/s]

Generating train split: 0 examples [00:00, ? examples/s]

Generating validation split: 0 examples [00:00, ? examples/s]

Generating test split: 0 examples [00:00, ? examples/s]

Generating test_french split: 0 examples [00:00, ? examples/s]

Generating test_chinese split: 0 examples [00:00, ? examples/s]

Generating test_arabic split: 0 examples [00:00, ? examples/s]

Generating test_german split: 0 examples [00:00, ? examples/s]

Generating test_portuguese split: 0 examples [00:00, ? examples/s]

Generating test_russian split: 0 examples [00:00, ? examples/s]

Generating test_spanish split: 0 examples [00:00, ? examples/s]

Success! Extracted 1273 pure German MedQA questions.

Here is the first German question:
The following are multiple choice questions (with answers) about medical knowledge.
 **Question:** Eine 44-jährige afroamerikanische Frau kommt zu ihrem Arzt für eine Routineuntersuchung. Sie macht sich Sorgen um Krebs, weil ihr Onkel vor einem Jahr an metastasierendem Melanom gestorben ist. Sie hat keine Vorgeschichte schwerer Krankheiten und nimmt keine Medikamente ein. Sie arbeitet seit 20 Jahren in einer Anwaltskanzlei und reist regelmäßig mit ihrem Ehemann in die Karibik. Die Untersuchung ihrer Haut zeigt keine abnormen Muttermale oder Warzen. Diese Frau hat das größte Risiko für welchen Typ von Melanom?
 (A) "Desmoplastisch"
 (B) "Knötchenförmig"
 (C) Acral lentiginous
 (D) "Superficial spreading" - oberflächliche Ausbreitung
 **Answer:**(

In [ ]:
import pandas as pd

# 1. Load the data we made earlier
df_german = pd.DataFrame(dataset['test_german'])

# 2. Keep ONLY the ID, the Question, and the Solution columns!
clean_df = df_german[['identifier', 'prompt_no_answer', 'prompt']].copy()

# Let's rename the columns so they make perfect sense to you
clean_df.columns = ['ID', 'German_Question', 'Question_With_Correct_Answer']

# 3. Save it!
clean_df.to_csv("Cleaned_German_MedQA.csv", index=False)

print("Successfully cleaned the dataset! All the confusing 'fewshot' columns are gone.")

Successfully cleaned the dataset! All the confusing 'fewshot' columns are gone.

In [ ]:
import pandas as pd

# 1. Load the German test data
df_german = pd.DataFrame(dataset['test_german'])

# 2. MAGIC TRICK: Extract ONLY the last letter from the 'prompt' column
# Since the text ends with "**Answer:**(C", we tell Python to just grab the very last character ([-1])
df_german['Correct_Letter'] = df_german['prompt'].str[-1]

# 3. Create our final, perfectly clean table
clean_df = df_german[['identifier', 'prompt_no_answer', 'Correct_Letter']].copy()

# Rename the columns so they are easy to understand
clean_df.columns = ['ID', 'German_Question', 'Correct_Answer']

# 4. Save it
clean_df.to_csv("Perfect_German_MedQA.csv", index=False)

# Print the first 3 rows to prove it worked!
print(clean_df.head(3))

    ID                                    German_Question Correct_Answer
0   82  The following are multiple choice questions (w...              C
1  465  The following are multiple choice questions (w...              C
2  236  The following are multiple choice questions (w...              A

In [ ]:
from datasets import load_dataset
import pandas as pd

print("Downloading the data...")
dataset = load_dataset("BioMistral/BioInstructQA", "MedQA", trust_remote_code=True)

# 1. Get the GERMAN data and clean it
df_ger = pd.DataFrame(dataset['test_german'])
clean_ger = df_ger[['identifier', 'prompt_no_answer']].copy()
clean_ger.columns = ['ID', 'German_Question']

# 2. Get the ENGLISH data (from the standard 'test' split)
df_eng = pd.DataFrame(dataset['test'])
clean_eng = df_eng[['identifier', 'prompt_no_answer', 'prompt']].copy()

# We grab the answer letter (A, B, C, or D) from the English text
clean_eng['Correct_Answer'] = clean_eng['prompt'].str[-1]
clean_eng = clean_eng[['identifier', 'prompt_no_answer', 'Correct_Answer']]
clean_eng.columns = ['ID', 'English_Question', 'Correct_Answer']

# 3. THE MAGIC STEP: Merge (Join) using the ID!
# This guarantees that ID 82 in English is locked to ID 82 in German, no matter the row order.
merged_df = pd.merge(clean_eng, clean_ger, on='ID', how='inner')

# Reorder the columns so they look nice
merged_df = merged_df[['ID', 'English_Question', 'German_Question', 'Correct_Answer']]

# 4. Save it!
merged_df.to_csv("Bilingual_MedQA_Matched.csv", index=False)

print(f"\nSuccess! {len(merged_df)} questions were perfectly synchronized by their IDs.")
print("\nHere is Row 1 to verify:")
print("ID:", merged_df.iloc[0]['ID'])
print("ENG:", merged_df.iloc[0]['English_Question'][:200], "...")
print("GER:", merged_df.iloc[0]['German_Question'][:200], "...")

Downloading the data...

Downloading builder script: 0.00B [00:00, ?B/s]

Downloading readme: 0.00B [00:00, ?B/s]

Success! 1273 questions were perfectly synchronized by their IDs.

Here is Row 1 to verify:
ID: 82
ENG: The following are multiple choice questions (with answers) about medical knowledge.
 **Question:** A 44-year-old African-American woman comes to the physician for a routine examination. She is concer ...
GER: The following are multiple choice questions (with answers) about medical knowledge.
 **Question:** Eine 44-jährige afroamerikanische Frau kommt zu ihrem Arzt für eine Routineuntersuchung. Sie macht s ...

### This dataset is for different medical fields ! We need to filter it and search for status treated by General Practitioner

In [ ]:
import pandas as pd

print("Loading the bilingual benchmark...")
# 1. Load the dataset you just created
df = pd.read_csv("Bilingual_MedQA_Matched.csv")

# 2. Define our GP Keywords (English and German!)
# We use root words so we catch variations (e.g., "depressi" catches depression, depressive, depressiv)
gp_keywords = [
    # 1. Hypertension
    "hypertension", "bluthochdruck", "hypertonie", "blood pressure", "blutdruck",
    # 2. Diabetes
    "diabetes", "diabetic", "diabetiker",
    # 3. Asthma
    "asthma", "asthmatic", "asthmatiker",
    # 4. COPD
    "copd", "obstructive pulmonary", "obstruktive lungen",
    # 5. Coronary Heart Disease
    "coronary", "khk", "koronare", "herzinfarkt", "myocardial infarction", "angina",
    # 6. Heart Failure
    "heart failure", "herzinsuffizienz",
    # 7. Chronic Back Pain
    "back pain", "kreuzschmerz", "rückenschmerz", "lumbar",
    # 8. Depression
    "depression", "depressive", "depressiv",
    # 9. Osteoarthritis
    "osteoarthritis", "arthrose", "joint pain", "gelenkschmerz",
    # 10. CKD & Dementia
    "kidney disease", "nierenkrankheit", "niereninsuffizienz", "renal failure", "ckd",
    "dementia", "demenz", "alzheimer"
]

# 3. Create a massive Regex (Search) Pattern: "word1|word2|word3"
pattern = '|'.join(gp_keywords)

print("Filtering for GP Top 10 Diseases...")
# 4. Apply the filter: Keep the row IF the English OR German question contains a keyword
filtered_df = df[
    df['English_Question'].str.contains(pattern, case=False, na=False) |
    df['German_Question'].str.contains(pattern, case=False, na=False)
].copy()

# 5. Save the final Master's Thesis Benchmark!
filtered_df.to_csv("GP_Top10_Bilingual_Benchmark.csv", index=False)

# Let's see how many questions survived!
print(f"\nOriginal size: {len(df)} questions.")
print(f"New GP-specific size: {len(filtered_df)} questions.")
print("\nSuccess! Saved as 'GP_Top10_Bilingual_Benchmark.csv'.")

Loading the bilingual benchmark...
Filtering for GP Top 10 Diseases...

Original size: 1273 questions.
New GP-specific size: 715 questions.

Success! Saved as 'GP_Top10_Bilingual_Benchmark.csv'.

Modern AI datasets are saved using a universal text format called UTF-8, which perfectly understands German umlauts (ä, ö, ü, ß).

In [ ]:
# 2. Save it with the Windows Excel fix! ('utf-8-sig')
filtered_df.to_csv("GP_Top10_Bilingual_Excel_Fixed.csv", encoding="utf-8-sig", index=False)

In [ ]:
# display the whole data in a row
pd.set_option('display.max_colwidth', None)
filtered_df.head()

,ID,English_Question,German_Question,Correct_Answer
1,465,"The following are multiple choice questions (with answers) about medical knowledge. \n **Question:** A 45-year-old female presents to the emergency department with gross hematuria and acute, colicky flank pain. She denies any previous episodes of hematuria. She reports taking high doses of acetaminophen and aspirin over several weeks due to persistent upper back pain. The patient’s blood pressure and temperature are normal, but she is found to have proteinuria. Physical examination is negative for palpable flank masses. Which of the following is the most likely diagnosis: \n (A) Diffuse cortical necrosis \n (B) Chronic pyelonephritis \n (C) Papillary necrosis \n (D) Acute Nephrolithiasis \n **Answer:**(","The following are multiple choice questions (with answers) about medical knowledge. \n **Question:** ""Eine 45-jährige Frau stellt sich in der Notaufnahme mit sichtbarem Blut im Urin und akuten, kolikartigen Flankenschmerzen vor. Sie verneint frühere Episoden von Hämaturie. Sie berichtet, dass sie aufgrund anhaltender Schmerzen im oberen Rücken über mehrere Wochen hohe Dosen Acetaminophen und Aspirin eingenommen hat. Der Blutdruck und die Temperatur der Patientin sind normal, aber es wird eine Proteinurie festgestellt. Die körperliche Untersuchung ergibt keinen tastbaren Flankentumor. Welche der folgenden Diagnosen ist am wahrscheinlichsten:"" \n (A) ""Difuse kortikale Nekrose"" \n (B) ""Chronische Pyelonephritis"" \n (C) ""Papilläre Nekrose"" \n (D) ""Akute Nephrolithiasis"" \n **Answer:**(",C
3,481,"The following are multiple choice questions (with answers) about medical knowledge. \n **Question:** Current recommendations state that a single hemoglobin A1c value of greater than 6.5% is diagnostic of diabetes mellitus. If this 6.5% cut-off is to be increased to 7.0%, which of the following would be true? \n (A) Increase in false negative test results \n (B) Increase in false positive test results \n (C) Decrease in true negative test results \n (D) Increase in true positive test results \n **Answer:**(","The following are multiple choice questions (with answers) about medical knowledge. \n **Question:** ""Nach aktuellen Empfehlungen bedeutet ein einzelner Hämoglobin A1c-Wert von über 6,5% eine Diagnose von Diabetes mellitus. Wenn dieser Grenzwert von 6,5% auf 7,0% erhöht werden soll, welches der folgenden Aussagen wäre wahr?"" \n (A) ""Zunahme falsch negativer Testergebnisse"" \n (B) ""Zunahme von falsch positiven Testergebnissen"" \n (C) ""Abnahme der wahren negativen Testergebnisse"" \n (D) ""Anstieg der wahren positiven Testergebnisse"" \n **Answer:**(",A
11,585,"The following are multiple choice questions (with answers) about medical knowledge. \n **Question:** A 55-year-old man is brought to the emergency department 12 hours after the sudden onset of shortness of breath and substernal chest pain at rest; the pain is increased by inspiration. He has also had a nonproductive cough, fever, and malaise for the past 5 days. He does not smoke or use illicit drugs. His temperature is 38°C (100.4°F), pulse is 125/min, respirations are 32/min, and blood pressure is 85/45 mm Hg. Physical examination shows distended neck veins. Auscultation of the chest discloses bilateral basilar rales and muffled heart sounds. An ECG shows sinus tachycardia, diffuse ST segment elevation, low voltage QRS complexes, and fluctuating R wave amplitude. Which of the following is the most likely diagnosis? \n (A) Kawasaki disease \n (B) Rheumatic fever \n (C) Infective endocarditis \n (D) Cardiac tamponade \n **Answer:**(","The following are multiple choice questions (with answers) about medical knowledge. \n **Question:** Ein 55-jähriger Mann wird 12 Stunden nach dem plötzlichen Auftreten von Atemnot und substernalem Brustschmerz in die Notaufnahme gebracht; der Schmerz wird durch Einatmen verstärkt. Er hatte in den letzten 5 Tagen auch einen nicht produktiven Husten, Fieber und Abgeschlagenheit. Er raucht nicht und nimmt keine illegalen Drogen. Seine Temperatur beträgt 38°C, der Puls 125/min, die Atemfrequenz 32/min und der Blutdruck 85/45 mm Hg. Bei der körperlichen Untersuchung sind die Halsvenen erweitert. Die Auskultation der Lunge zeigt bilaterale basale Rasselgeräusche und gedämpfte Herztöne. Ein EKG zeigt eine Sinustachykardie, eine diffuse ST-Streckenhebung, geringe QRS-Komplexe und schwankende R-Wellen-Amplitude. Welche der folgenden Diagnosen ist am wahrscheinlichsten? \n (A) ""Kawasaki-Krankheit"" \n (B) ""Rheumatisches Fieber"" \n (C) Infektiöse Endokarditis \n (D) Kardiakale Tamponade \n **Answer:**(",D
12,680,"The following are multiple choice questions (with answers) about medical knowledge. \n **Question:** A 25-year-old man presents to the office because of extreme fatigue for the past 2 days. He is also worried about his skin looking yellow. He does not have any other complaints and denies fever and headache. He admits to using illicit intravenous drugs in the past. He does not have any immunization records because he moved from Africa to the US at the age of 18. His vital signs are as follows: heart rate 72/min, respiratory rate 14/min, temperature 37.9°C (100.2°F), and blood pressure 100/74 mm Hg. Physical examination is not significant except for mild diffuse abdominal tenderness. His blood is drawn for routine tests and shows an alanine aminotransferase level (ALT) of 2,000 IU/L. A hepatitis viral panel is ordered which shows:\nAnti-HAV IgM negative\nHBsAg positive\nAnti-HBs negative\nIgM anti-HBc positive\nAnti-HCV negative\nAnti-HDV negative\nWhat is the most likely diagnosis? \n (A) Past hepatitis B infection \n (B) Acute hepatitis A \n (C) Acute hepatitis D superinfection \n (D) Acute hepatitis B \n **Answer:**(","The following are multiple choice questions (with answers) about medical knowledge. \n **Question:** Ein 25-jähriger Mann kommt wegen extremer Müdigkeit in den letzten 2 Tagen in die Praxis. Er macht sich auch Sorgen, dass seine Haut gelb aussieht. Er hat keine weiteren Beschwerden und leugnet Fieber und Kopfschmerzen. Er gibt zu, in der Vergangenheit illegale intravenöse Drogen konsumiert zu haben. Er hat keine Impfungsunterlagen, da er im Alter von 18 Jahren von Afrika in die USA gezogen ist. Seine Vitalzeichen sind wie folgt: Herzfrequenz 72/Minute, Atemfrequenz 14/Minute, Temperatur 37,9°C (100,2°F) und Blutdruck 100/74 mm Hg. Bei der körperlichen Untersuchung ist nichts Besonderes festzustellen, außer einer leichten diffusen Bauchempfindlichkeit. Sein Blut wird für Routineuntersuchungen entnommen und zeigt einen Alanin-Aminotransferase-Wert (ALT) von 2.000 IU/L. Es wird eine Hepatitis-Virus-Panel-Untersuchung angeordnet, die folgendes zeigt:\nAnti-HAV IgM negativ\nHBsAg positiv\nAnti-HBs negativ\nIgM anti-HBc positiv\nAnti-HCV negativ\nAnti-HDV negativ\nWas ist die wahrscheinlichste Diagnose? \n (A) Vorherige Hepatitis-B-Infektion \n (B) ""Akute Hepatitis A"" \n (C) Akute Hepatitis D-Superinfektion \n (D) ""Akute Hepatitis B"" \n **Answer:**(",D
13,1164,"The following are multiple choice questions (with answers) about medical knowledge. \n **Question:** An 80-year-old African American man is brought to the emergency department in a confused state with history of general illness for the past week. He is known to be hypertensive, but noncompliant with medications for the last 20 years. Physical examination reveals dry skin, ecchymoses, and conjunctival pallor. His blood pressure is 180/99 mm Hg, heart rate is 89/min, and respiratory rate is 17/min. The initial laboratory results are remarkable for hemoglobin of 10 g/dL, mean corpuscular volume of 90 μm3, platelet count of 200,000/mm3, blood urea nitrogen of 29 mg/dL, and creatinine of 2.1 mg/dL. Which of the following would be the best initial management for this patient's condition? \n (A) Angiotensin-converting-enzyme inhibitor (ACEI) \n (B) Angiotensin II receptor blocker (ARB) \n (C) Calcium channel blocker (CCB) \n (D) Thiazide \n **Answer:**(","The following are multiple choice questions (with answers) about medical knowledge. \n **Question:** Ein 80-jähriger afroamerikanischer Mann wird in einem verwirrten Zustand in die Notaufnahme gebracht, nachdem er in der letzten Woche allgemein krank war. Es ist bekannt, dass er an Hypertonie leidet, jedoch seit den letzten 20 Jahren nicht konform mit seinen Medikamenten war. Die körperliche Untersuchung zeigt trockene Haut, Hämatome und eine blasse Bindehaut. Sein Blutdruck beträgt 180/99 mmHg, seine Herzfrequenz beträgt 89/min und seine Atemfrequenz beträgt 17/min. Die initialen Laborergebnisse weisen auf einen Hämoglobinspiegel von 10 g/dL, ein mittleres korpuskuläres Volumen von 90 µm3, eine Thrombozytenzahl von 200.000/mm3, einen Blutharnstoff-Stickstoffwert von 29 mg/dL und einen Kreatininwert von 2,1 mg/dL hin. Welche der folgenden Maßnahmen wäre die beste erste Behandlung für den Zustand dieses Patienten? \n (A) Angiotensin-Converting-Enzym-Hemmer (ACE-Hemmer) \n (B) Angiotensin-II-Rezeptorblocker (ARB) \n (C) Calciumkanalblocker (CCB) \n (D) Thiazide \n **Answer:**(",A

Because our Benschmark contains the Multiple choice answers , and we need to know how the LLM thinks without giving it answers , we add the questions without the MCQ answers to the dataset. Here is the final result !

In [ ]:
import pandas as pd
# Load the dataset
df_openQ = pd.read_csv('/content/GP_Top10_Bilingual_Open_Ended.csv')

In [ ]:
# DROP THE EMPTY COLUMN
df_openQ.drop(columns=['Unnamed: 6'], inplace=False)

,ID,English_Question,German_Question,Correct_Answer,English_Open_Question,German_Open_Question
0,465,"The following are multiple choice questions (with answers) about medical knowledge. \n **Question:** A 45-year-old female presents to the emergency department with gross hematuria and acute, colicky flank pain. She denies any previous episodes of hematuria. She reports taking high doses of acetaminophen and aspirin over several weeks due to persistent upper back pain. The patient’s blood pressure and temperature are normal, but she is found to have proteinuria. Physical examination is negative for palpable flank masses. Which of the following is the most likely diagnosis: \n (A) Diffuse cortical necrosis \n (B) Chronic pyelonephritis \n (C) Papillary necrosis \n (D) Acute Nephrolithiasis \n **Answer:**(","The following are multiple choice questions (with answers) about medical knowledge. \n **Question:** ""Eine 45-jährige Frau stellt sich in der Notaufnahme mit sichtbarem Blut im Urin und akuten, kolikartigen Flankenschmerzen vor. Sie verneint frühere Episoden von Hämaturie. Sie berichtet, dass sie aufgrund anhaltender Schmerzen im oberen Rücken über mehrere Wochen hohe Dosen Acetaminophen und Aspirin eingenommen hat. Der Blutdruck und die Temperatur der Patientin sind normal, aber es wird eine Proteinurie festgestellt. Die körperliche Untersuchung ergibt keinen tastbaren Flankentumor. Welche der folgenden Diagnosen ist am wahrscheinlichsten:"" \n (A) ""Difuse kortikale Nekrose"" \n (B) ""Chronische Pyelonephritis"" \n (C) ""Papilläre Nekrose"" \n (D) ""Akute Nephrolithiasis"" \n **Answer:**(",C,"A 45-year-old female presents to the emergency department with gross hematuria and acute, colicky flank pain. She denies any previous episodes of hematuria. She reports taking high doses of acetaminophen and aspirin over several weeks due to persistent upper back pain. The patient’s blood pressure and temperature are normal, but she is found to have proteinuria. Physical examination is negative for palpable flank masses. What is the most likely diagnosis:","Eine 45-jährige Frau stellt sich in der Notaufnahme mit sichtbarem Blut im Urin und akuten, kolikartigen Flankenschmerzen vor. Sie verneint frühere Episoden von Hämaturie. Sie berichtet, dass sie aufgrund anhaltender Schmerzen im oberen Rücken über mehrere Wochen hohe Dosen Acetaminophen und Aspirin eingenommen hat. Der Blutdruck und die Temperatur der Patientin sind normal, aber es wird eine Proteinurie festgestellt. Die körperliche Untersuchung ergibt keinen tastbaren Flankentumor. Welche Diagnose ist am wahrscheinlichsten:"
1,481,"The following are multiple choice questions (with answers) about medical knowledge. \n **Question:** Current recommendations state that a single hemoglobin A1c value of greater than 6.5% is diagnostic of diabetes mellitus. If this 6.5% cut-off is to be increased to 7.0%, which of the following would be true? \n (A) Increase in false negative test results \n (B) Increase in false positive test results \n (C) Decrease in true negative test results \n (D) Increase in true positive test results \n **Answer:**(","The following are multiple choice questions (with answers) about medical knowledge. \n **Question:** ""Nach aktuellen Empfehlungen bedeutet ein einzelner Hämoglobin A1c-Wert von über 6,5% eine Diagnose von Diabetes mellitus. Wenn dieser Grenzwert von 6,5% auf 7,0% erhöht werden soll, welches der folgenden Aussagen wäre wahr?"" \n (A) ""Zunahme falsch negativer Testergebnisse"" \n (B) ""Zunahme von falsch positiven Testergebnissen"" \n (C) ""Abnahme der wahren negativen Testergebnisse"" \n (D) ""Anstieg der wahren positiven Testergebnisse"" \n **Answer:**(",A,"Current recommendations state that a single hemoglobin A1c value of greater than 6.5% is diagnostic of diabetes mellitus. If this 6.5% cut-off is to be increased to 7.0%, What would be true?","Nach aktuellen Empfehlungen bedeutet ein einzelner Hämoglobin A1c-Wert von über 6,5% eine Diagnose von Diabetes mellitus. Wenn dieser Grenzwert von 6,5% auf 7,0% erhöht werden soll, Welches Aussagen wäre wahr?"
2,585,"The following are multiple choice questions (with answers) about medical knowledge. \n **Question:** A 55-year-old man is brought to the emergency department 12 hours after the sudden onset of shortness of breath and substernal chest pain at rest; the pain is increased by inspiration. He has also had a nonproductive cough, fever, and malaise for the past 5 days. He does not smoke or use illicit drugs. His temperature is 38°C (100.4°F), pulse is 125/min, respirations are 32/min, and blood pressure is 85/45 mm Hg. Physical examination shows distended neck veins. Auscultation of the chest discloses bilateral basilar rales and muffled heart sounds. An ECG shows sinus tachycardia, diffuse ST segment elevation, low voltage QRS complexes, and fluctuating R wave amplitude. Which of the following is the most likely diagnosis? \n (A) Kawasaki disease \n (B) Rheumatic fever \n (C) Infective endocarditis \n (D) Cardiac tamponade \n **Answer:**(","The following are multiple choice questions (with answers) about medical knowledge. \n **Question:** Ein 55-jähriger Mann wird 12 Stunden nach dem plötzlichen Auftreten von Atemnot und substernalem Brustschmerz in die Notaufnahme gebracht; der Schmerz wird durch Einatmen verstärkt. Er hatte in den letzten 5 Tagen auch einen nicht produktiven Husten, Fieber und Abgeschlagenheit. Er raucht nicht und nimmt keine illegalen Drogen. Seine Temperatur beträgt 38°C, der Puls 125/min, die Atemfrequenz 32/min und der Blutdruck 85/45 mm Hg. Bei der körperlichen Untersuchung sind die Halsvenen erweitert. Die Auskultation der Lunge zeigt bilaterale basale Rasselgeräusche und gedämpfte Herztöne. Ein EKG zeigt eine Sinustachykardie, eine diffuse ST-Streckenhebung, geringe QRS-Komplexe und schwankende R-Wellen-Amplitude. Welche der folgenden Diagnosen ist am wahrscheinlichsten? \n (A) ""Kawasaki-Krankheit"" \n (B) ""Rheumatisches Fieber"" \n (C) Infektiöse Endokarditis \n (D) Kardiakale Tamponade \n **Answer:**(",D,"A 55-year-old man is brought to the emergency department 12 hours after the sudden onset of shortness of breath and substernal chest pain at rest; the pain is increased by inspiration. He has also had a nonproductive cough, fever, and malaise for the past 5 days. He does not smoke or use illicit drugs. His temperature is 38°C (100.4°F), pulse is 125/min, respirations are 32/min, and blood pressure is 85/45 mm Hg. Physical examination shows distended neck veins. Auscultation of the chest discloses bilateral basilar rales and muffled heart sounds. An ECG shows sinus tachycardia, diffuse ST segment elevation, low voltage QRS complexes, and fluctuating R wave amplitude. What is the most likely diagnosis?","Ein 55-jähriger Mann wird 12 Stunden nach dem plötzlichen Auftreten von Atemnot und substernalem Brustschmerz in die Notaufnahme gebracht; der Schmerz wird durch Einatmen verstärkt. Er hatte in den letzten 5 Tagen auch einen nicht produktiven Husten, Fieber und Abgeschlagenheit. Er raucht nicht und nimmt keine illegalen Drogen. Seine Temperatur beträgt 38°C, der Puls 125/min, die Atemfrequenz 32/min und der Blutdruck 85/45 mm Hg. Bei der körperlichen Untersuchung sind die Halsvenen erweitert. Die Auskultation der Lunge zeigt bilaterale basale Rasselgeräusche und gedämpfte Herztöne. Ein EKG zeigt eine Sinustachykardie, eine diffuse ST-Streckenhebung, geringe QRS-Komplexe und schwankende R-Wellen-Amplitude. Welche Diagnose ist am wahrscheinlichsten?"
3,680,"The following are multiple choice questions (with answers) about medical knowledge. \n **Question:** A 25-year-old man presents to the office because of extreme fatigue for the past 2 days. He is also worried about his skin looking yellow. He does not have any other complaints and denies fever and headache. He admits to using illicit intravenous drugs in the past. He does not have any immunization records because he moved from Africa to the US at the age of 18. His vital signs are as follows: heart rate 72/min, respiratory rate 14/min, temperature 37.9°C (100.2°F), and blood pressure 100/74 mm Hg. Physical examination is not significant except for mild diffuse abdominal tenderness. His blood is drawn for routine tests and shows an alanine aminotransferase level (ALT) of 2,000 IU/L. A hepatitis viral panel is ordered which shows:\nAnti-HAV IgM negative\nHBsAg positive\nAnti-HBs negative\nIgM anti-HBc positive\nAnti-HCV negative\nAnti-HDV negative\nWhat is the most likely diagnosis? \n (A) Past hepatitis B infection \n (B) Acute hepatitis A \n (C) Acute hepatitis D superinfection \n (D) Acute hepatitis B \n **Answer:**(","The following are multiple choice questions (with answers) about medical knowledge. \n **Question:** Ein 25-jähriger Mann kommt wegen extremer Müdigkeit in den letzten 2 Tagen in die Praxis. Er macht sich auch Sorgen, dass seine Haut gelb aussieht. Er hat keine weiteren Beschwerden und leugnet Fieber und Kopfschmerzen. Er gibt zu, in der Vergangenheit illegale intravenöse Drogen konsumiert zu haben. Er hat keine Impfungsunterlagen, da er im Alter von 18 Jahren von Afrika in die USA gezogen ist. Seine Vitalzeichen sind wie folgt: Herzfrequenz 72/Minute, Atemfrequenz 14/Minute, Temperatur 37,9°C (100,2°F) und Blutdruck 100/74 mm Hg. Bei der körperlichen Untersuchung ist nichts Besonderes festzustellen, außer einer leichten diffusen Bauchempfindlichkeit. Sein Blut wird für Routineuntersuchungen entnommen und zeigt einen Alanin-Aminotransferase-Wert (ALT) von 2.000 IU/L. Es wird eine Hepatitis-Virus-Panel-Untersuchung angeordnet, die folgendes zeigt:\nAnti-HAV IgM negativ\nHBsAg positiv\nAnti-HBs negativ\nIgM anti-HBc positiv\nAnti-HCV negativ\nAnti-HDV negativ\nWas ist die wahrscheinlichste Diagnose? \n (A) Vorherige Hepatitis-B-Infektion \n (B) ""Akute Hepatitis A"" \n (C) Akute Hepatitis D-Superinfektion \n (D) ""Akute Hepatitis B"" \n **Answer:**(",D,"A 25-year-old man presents to the office because of extreme fatigue for the past 2 days. He is also worried about his skin looking yellow. He does not have any other complaints and denies fever and headache. He admits to using illicit intravenous drugs in the past. He does not have any immunization records because he moved from Africa to the US at the age of 18. His vital signs are as follows: heart rate 72/min, respiratory rate 14/min, temperature 37.9°C (100.2°F), and blood pressure 100/74 mm Hg. Physical examination is not significant except for mild diffuse abdominal tenderness. His blood is drawn for routine tests and shows an alanine aminotransferase level (ALT) of 2,000 IU/L. A hepatitis viral panel is ordered which shows:\nAnti-HAV IgM negative\nHBsAg positive\nAnti-HBs negative\nIgM anti-HBc positive\nAnti-HCV negative\nAnti-HDV negative\nWhat is the most likely diagnosis?","Ein 25-jähriger Mann kommt wegen extremer Müdigkeit in den letzten 2 Tagen in die Praxis. Er macht sich auch Sorgen, dass seine Haut gelb aussieht. Er hat keine weiteren Beschwerden und leugnet Fieber und Kopfschmerzen. Er gibt zu, in der Vergangenheit illegale intravenöse Drogen konsumiert zu haben. Er hat keine Impfungsunterlagen, da er im Alter von 18 Jahren von Afrika in die USA gezogen ist. Seine Vitalzeichen sind wie folgt: Herzfrequenz 72/Minute, Atemfrequenz 14/Minute, Temperatur 37,9°C (100,2°F) und Blutdruck 100/74 mm Hg. Bei der körperlichen Untersuchung ist nichts Besonderes festzustellen, außer einer leichten diffusen Bauchempfindlichkeit. Sein Blut wird für Routineuntersuchungen entnommen und zeigt einen Alanin-Aminotransferase-Wert (ALT) von 2.000 IU/L. Es wird eine Hepatitis-Virus-Panel-Untersuchung angeordnet, die folgendes zeigt:\nAnti-HAV IgM negativ\nHBsAg positiv\nAnti-HBs negativ\nIgM anti-HBc positiv\nAnti-HCV negativ\nAnti-HDV negativ\nWas ist die wahrscheinlichste Diagnose?"
4,1164,"The following are multiple choice questions (with answers) about medical knowledge. \n **Question:** An 80-year-old African American man is brought to the emergency department in a confused state with history of general illness for the past week. He is known to be hypertensive, but noncompliant with medications for the last 20 years. Physical examination reveals dry skin, ecchymoses, and conjunctival pallor. His blood pressure is 180/99 mm Hg, heart rate is 89/min, and respiratory rate is 17/min. The initial laboratory results are remarkable for hemoglobin of 10 g/dL, mean corpuscular volume of 90 μm3, platelet count of 200,000/mm3, blood urea nitrogen of 29 mg/dL, and creatinine of 2.1 mg/dL. Which of the following would be the best initial management for this patient's condition? \n (A) Angiotensin-converting-enzyme inhibitor (ACEI) \n (B) Angiotensin II receptor blocker (ARB) \n (C) Calcium channel blocker (CCB) \n (D) Thiazide \n **Answer:**(","The following are multiple choice questions (with answers) about medical knowledge. \n **Question:** Ein 80-jähriger afroamerikanischer Mann wird in einem verwirrten Zustand in die Notaufnahme gebracht, nachdem er in der letzten Woche allgemein krank war. Es ist bekannt, dass er an Hypertonie leidet, jedoch seit den letzten 20 Jahren nicht konform mit seinen Medikamenten war. Die körperliche Untersuchung zeigt trockene Haut, Hämatome und eine blasse Bindehaut. Sein Blutdruck beträgt 180/99 mmHg, seine Herzfrequenz beträgt 89/min und seine Atemfrequenz beträgt 17/min. Die initialen Laborergebnisse weisen auf einen Hämoglobinspiegel von 10 g/dL, ein mittleres korpuskuläres Volumen von 90 µm3, eine Thrombozytenzahl von 200.000/mm3, einen Blutharnstoff-Stickstoffwert von 29 mg/dL und einen Kreatininwert von 2,1 mg/dL hin. Welche der folgenden Maßnahmen wäre die beste erste Behandlung für den Zustand dieses Patienten? \n (A) Angiotensin-Converting-Enzym-Hemmer (ACE-Hemmer) \n (B) Angiotensin-II-Rezeptorblocker (ARB) \n (C) Calciumkanalblocker (CCB) \n (D) Thiazide \n **Answer:**(",A,"An 80-year-old African American man is brought to the emergency department in a confused state with history of general illness for the past week. He is known to be hypertensive, but noncompliant with medications for the last 20 years. Physical examination reveals dry skin, ecchymoses, and conjunctival pallor. His blood pressure is 180/99 mm Hg, heart rate is 89/min, and respiratory rate is 17/min. The initial laboratory results are remarkable for hemoglobin of 10 g/dL, mean corpuscular volume of 90 μm3, platelet count of 200,000/mm3, blood urea nitrogen of 29 mg/dL, and creatinine of 2.1 mg/dL. What would be the best initial management for this patient's condition?","Ein 80-jähriger afroamerikanischer Mann wird in einem verwirrten Zustand in die Notaufnahme gebracht, nachdem er in der letzten Woche allgemein krank war. Es ist bekannt, dass er an Hypertonie leidet, jedoch seit den letzten 20 Jahren nicht konform mit seinen Medikamenten war. Die körperliche Untersuchung zeigt trockene Haut, Hämatome und eine blasse Bindehaut. Sein Blutdruck beträgt 180/99 mmHg, seine Herzfrequenz beträgt 89/min und seine Atemfrequenz beträgt 17/min. Die initialen Laborergebnisse weisen auf einen Hämoglobinspiegel von 10 g/dL, ein mittleres korpuskuläres Volumen von 90 µm3, eine Thrombozytenzahl von 200.000/mm3, einen Blutharnstoff-Stickstoffwert von 29 mg/dL und einen Kreatininwert von 2,1 mg/dL hin. Welche Maßnahmen wäre die beste erste Behandlung für den Zustand dieses Patienten?"
...,...,...,...,...,...,...

In [ ]:
df_openQ.to_csv("GP_Top10_Bilingual_Open_EndedQ.csv", encoding="utf-8-sig", index=False)

In [ ]:
from google.colab import files
files.download('GP_Top10_Bilingual_Open_EndedQ.csv')

## Our Benschmark is finally ready :)